server:
  port: 9011
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  application:
    name: goods
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://139.198.178.244:3306/changgou_goods?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: password

eureka:
  client:
    service‐url:
      defaultZone: http://127.0.0.1:6868/eureka
  instance:
    prefer‐ip‐address: true
feign:
  hystrix:
    enabled: true
#hystrix 配置
hystrix:
  command:
    default:
     execution:
      timeout:
        #如果enabled设置为false，则请求超时交给ribbon控制
        enabled: true
      isolation:
        strategy: SEMAPHORE